#!/usr/bin/env bash

# if [ -n "${__gitlab_tokens_included__}" ]; then return 0; fi
export __gitlab_tokens_included__=true

# =============================== > Settings < =============================== #
dependencies=("jq" "curl")

git_registry_port=5005
git_api_version=4

if [ -z "${GITLAB_TOKENS_DIR}" ]; then
    export GITLAB_TOKENS_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
fi

echo "GITLAB_TOKENS_DIR: $GITLAB_TOKENS_DIR"

# ────────────────────────────────── <end> ─────────────────────────────────── #

# ========================== > Source submodules < =========================== #
cd ${GITLAB_TOKENS_DIR}/submodules/bash-doc &&
    source ./bash-doc-init
cd ${GITLAB_TOKENS_DIR}
# ────────────────────────────────── <end> ─────────────────────────────────── #

# ============================= > Source files < ============================= #
cd ${GITLAB_TOKENS_DIR}/functions
source ./check_dependency
source ./git_api
source ./git_api_secret_set
source ./git_repo_info
source ./git_repo_id
source ./git_token_access
source ./git_token_create
source ./git_token_delete
source ./git_token_id_get
source ./git_token_renew
source ./git_token_rotate
source ./git_token_valid
source ./git_token_valid_docker
source ./git_token_valid_enroot
source ./make_file_path
source ./normalize_path
source ./read_from_file
source ./read_non_blocking
source ./token_name
cd ${GITLAB_TOKENS_DIR}/
# ────────────────────────────────── <end> ─────────────────────────────────── #

# ========================== > Check dependencies < ========================== #
# Dependencies are declared in the 'settings' section
check_dependencies --commands "${dependencies[@]}"
# ────────────────────────────────── <end> ─────────────────────────────────── #

# ========================= > Export all functions < ========================= #
eval "$(declare -F | sed -e 's/-f /-fx /')" 
# ────────────────────────────────── <end> ─────────────────────────────────── #
