#!/usr/bin/env bash

if [ -n "${__gitlab_tokens_included__}" ]; then return 0; fi
export __gitlab_tokens_included__=true

# =============================== > Settings < =============================== #
dependencies=("jq" "curl")

git_registry_port=5005
git_api_version=4

if [ -z "${GITLAB_TOKENS_DIR}" ]; then
    GITLAB_TOKENS_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
fi

echo "GITLAB_TOKENS_DIR: $GITLAB_TOKENS_DIR"

# ────────────────────────────────── <end> ─────────────────────────────────── #

# ========================== > Source submodules < =========================== #
source ${GITLAB_TOKENS_DIR}/submodules/bash-doc/bash-doc-init
# ────────────────────────────────── <end> ─────────────────────────────────── #

# ============================= > Source files < ============================= #
source ${GITLAB_TOKENS_DIR}/functions/check_dependency
source ${GITLAB_TOKENS_DIR}/functions/git_api
source ${GITLAB_TOKENS_DIR}/functions/git_api_secret_set
source ${GITLAB_TOKENS_DIR}/functions/git_repo_info
source ${GITLAB_TOKENS_DIR}/functions/git_repo_id
source ${GITLAB_TOKENS_DIR}/functions/git_token_access
source ${GITLAB_TOKENS_DIR}/functions/git_token_create
source ${GITLAB_TOKENS_DIR}/functions/git_token_delete
source ${GITLAB_TOKENS_DIR}/functions/git_token_id_get
source ${GITLAB_TOKENS_DIR}/functions/git_token_renew
source ${GITLAB_TOKENS_DIR}/functions/git_token_rotate
source ${GITLAB_TOKENS_DIR}/functions/git_token_valid
source ${GITLAB_TOKENS_DIR}/functions/git_token_valid_docker
source ${GITLAB_TOKENS_DIR}/functions/git_token_valid_enroot
source ${GITLAB_TOKENS_DIR}/functions/make_file_path
source ${GITLAB_TOKENS_DIR}/functions/normalize_path
source ${GITLAB_TOKENS_DIR}/functions/read_from_file
source ${GITLAB_TOKENS_DIR}/functions/read_non_blocking
source ${GITLAB_TOKENS_DIR}/functions/token_name
# ────────────────────────────────── <end> ─────────────────────────────────── #

# ========================== > Check dependencies < ========================== #
# Dependencies are declared in the 'settings' section
check_dependencies --commands "${dependencies[@]}"
# ────────────────────────────────── <end> ─────────────────────────────────── #

# ========================= > Export all functions < ========================= #
eval "$(declare -F | sed -e 's/-f /-fx /')" 
# ────────────────────────────────── <end> ─────────────────────────────────── #
