#!/usr/bin/env bash

if [ -n "${__gitlab_tokens_included__}" ]; then return 0; fi
export __gitlab_tokens_included__=true

# =============================== > Settings < =============================== #
dependencies=("jq" "curl")

git_registry_port=5005
git_api_version=4

if [ -z "${GITLAB_TOKENS_DIR}" ]; then
    current_file=
    if [ -n "$BASH_VERSION" ]; then
        current_file="${BASH_SOURCE[0]}"
    elif [ -n "$ZSH_VERSION" ]; then
        current_file="${(%):-%x}"
    fi
    GITLAB_TOKENS_DIR="$(dirname $(readlink -f "${current_file}"))"
fi
# ────────────────────────────────── <end> ─────────────────────────────────── #

# ========================== > Source submodules < =========================== #
source ${GITLAB_TOKENS_DIR}/submodules/bash-aux/bash-aux-init
# ────────────────────────────────── <end> ─────────────────────────────────── #

# ============================= > Source files < ============================= #
source ${GITLAB_TOKENS_DIR}/functions/git_api
source ${GITLAB_TOKENS_DIR}/functions/git_api_secret_set
source ${GITLAB_TOKENS_DIR}/functions/git_repo_info
source ${GITLAB_TOKENS_DIR}/functions/git_repo_id
source ${GITLAB_TOKENS_DIR}/functions/git_token_access
source ${GITLAB_TOKENS_DIR}/functions/git_token_create
source ${GITLAB_TOKENS_DIR}/functions/git_token_delete
source ${GITLAB_TOKENS_DIR}/functions/git_token_id_get
source ${GITLAB_TOKENS_DIR}/functions/git_token_renew
source ${GITLAB_TOKENS_DIR}/functions/git_token_rotate
source ${GITLAB_TOKENS_DIR}/functions/git_token_valid
source ${GITLAB_TOKENS_DIR}/functions/git_token_valid_docker
source ${GITLAB_TOKENS_DIR}/functions/git_token_valid_enroot
source ${GITLAB_TOKENS_DIR}/functions/token_name
# ────────────────────────────────── <end> ─────────────────────────────────── #

# ========================== > Check dependencies < ========================== #
# Dependencies are declared in the 'settings' section
check_dependencies --commands "${dependencies[@]}"
# ────────────────────────────────── <end> ─────────────────────────────────── #

# ========================= > Export all functions < ========================= #
eval "$(declare -F |
    perl -p0e "s/declare\s+-f\s+(.*)\s*$/export -f \${1}/gmi" )"
# ────────────────────────────────── <end> ─────────────────────────────────── #
